### ISSUE TITLE
User Story and Acceptance Criteria

### ISSUE THREAD

**Issue by corgimaman** [corgimaman/groupProject#1]
AS A _____(user)________
I WANT____(goal)______
SO THAT ______(benefit)______

Things to consider:

1. Who is our audience?
2. What is the problem the product will address?
3. How does the product solve that problem?

Acceptance Criteria:

GIVEN (precondition)
WHEN (I do some action)
THEN (I expect some result)

**Comment by ferick8246** [comment]
AS A stressed employee 
I WANT to be able to tell off my supervisor or my annoying co-worker without actually doing myself or using profanity
SO THAT we can avoid an engagement between a supervisor and an employee where they are involved knowledge transfer about an impending vocational paradigm shift or in other words get fired 

GIVEN  I need a button that 
WHEN I click the button to generate a text 
THEN I am presented with duck quote
WHEN I the user feels ready to explode

**Comment by corgimaman** [comment]
GIVEN I am a stressed user at work
WHEN I need a way to blow off steam
THEN I go to a censored soundboard
WHEN I enter names into the input text
THEN the buttons will appear
WHEN I click on a button
THEN someone else reads out my frustration

**Comment by corgimaman** [comment]
AS A stressed employee
I WANT to be able to tell off my supervisor or my annoying co-worker, without actually doing it myself or using profanity
SO THAT we can avoid an engagement between a supervisor and an employee where they are involved in a knowledge transfer about an impending vocational paradigm shift...or in other words get fired
